title: Leena is so amazing
author: Leena is obviously the author
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  hello to whoever is reading this. Congradulations you've made it here, yay!

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima 
